spring:
  config:
    import: vault://
  application:
    name: spring-boot-vault-sample
  cloud:
    vault:
      uri: http://localhost:8200
      token: my-root
      fail-fast: true
      kv:
        enabled: true
        backend: secret
        default-context: ${spring.application.name}
